function createfigure(X1, YMatrix1, X2, Y1)
%CREATEFIGURE(X1, YMATRIX1, X2, Y1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  X2:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 26-May-2021 19:08:42

% Create figure
figure('InvertHardcopy','off','PaperUnits','centimeters','Color',[1 1 1],...
    'OuterPosition',[1 1 640 360]);

% Create axes
axes1 = axes('Units','pixels');
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,...
    'MarkerIndices',[1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50],...
    'MarkerSize',10,...
    'LineWidth',2);
set(plot1(1),'DisplayName','Ideal SGD','Marker','diamond');
set(plot1(2),'DisplayName','Stochastic ADMM','Marker','^');
set(plot1(3),'DisplayName','Geometric median','Marker','>');
set(plot1(4),'DisplayName','Median','Marker','<');
set(plot1(5),'DisplayName','SGD','MarkerSize',15,'Marker','pentagram',...
    'Color',[0.301 0.745 0.933]);

% Create plot
plot(X2,Y1,'DisplayName','RSA',...
    'MarkerIndices',[1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50],...
    'MarkerSize',10,...
    'Marker','v',...
    'LineWidth',2);

% Create xlabel
xlabel('Iteration');

% Create ylabel
ylabel({'Accuracy'},'HorizontalAlignment','center');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 100]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 1]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-1 1]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',20,'OuterPosition',[1 1 640 320],'XTick',...
    [0 20 40 60 80 100],'XTickLabel',{'0','200','400','600','800','1000'});
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','southeast','FontSize',22);

